"""Added Order model, updated User and Inventory models

Revision ID: 29f5ce44b4cb
Revises: e2e3831757af
Create Date: 2025-03-16 18:32:23.384705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f5ce44b4cb'
down_revision = 'e2e3831757af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
