"""Create Inventory Table

Revision ID: 600d1a807d89
Revises: c23d32361c06
Create Date: 2025-03-13 10:40:55.953489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600d1a807d89'
down_revision = 'c23d32361c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.drop_table('inventory_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventory')
    # ### end Alembic commands ###
