"""Add status field to Supply model

Revision ID: d20b06af0c9e
Revises: 15f3a0737c56
Create Date: 2025-04-01 04:59:08.303359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20b06af0c9e'
down_revision = '15f3a0737c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
